name: Update NTHU Events

on:
  schedule:
    - cron: "0 4 * * *" # 12:00 Asia/Taipei (UTC+8)
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run crawler
        run: python scripts/nthu_events_crawler.py

      - name: Commit and push if changed
        run: |
          if [[ -n "$(git status --porcelain data/nthu_events.json)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/nthu_events.json
            git commit -m "chore: update NTHU events"
            git push
          else
            echo "No changes to commit."
          fi
